ALTER TABLE user_otp
ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE tenant_request 
ADD COLUMN pincode VARCHAR(10),
ADD COLUMN landmark VARCHAR(10);


CREATE TABLE IF NOT EXISTS "subscription_payment" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"payment_type_id" INTEGER,
   "paid_on" DATE NOT NULL DEFAULT NULL,
   "amount" DOUBLE PRECISION,
	"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
	"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
	"modified_by" VARCHAR(255) NULL DEFAULT NULL,
	"modified_time" TIMESTAMP NULL DEFAULT NULL,
	FOREIGN KEY (payment_type_id) REFERENCES payment_type (id),
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS "subscription_invoice" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"payment_type_id" INTEGER,
    "tenant_id" INTEGER,
    "payment_id" INTEGER,
	"total_amount" DOUBLE PRECISION,
   "paid_amount" DOUBLE PRECISION,
	"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
	"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
	"modified_by" VARCHAR(255) NULL DEFAULT NULL,
	"modified_time" TIMESTAMP NULL DEFAULT NULL,
	 FOREIGN KEY (payment_type_id) REFERENCES payment_type ( id ),
	 FOREIGN KEY (tenant_id) REFERENCES tenant(id),
	 FOREIGN KEY (payment_id)REFERENCES subscription_payment(id),
	 PRIMARY KEY("id")
);

