-- Tenant Request Table: Captures onboarding requests


-- Approved tenant Table: Stores approved tenant
CREATE TABLE IF NOT EXISTS "tenant" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "schema_name" VARCHAR(255) UNIQUE NOT NULL,
    "client_id" VARCHAR(255) UNIQUE NOT NULL,
    "client_url" VARCHAR(255),
    "name" VARCHAR(255),
    "email" VARCHAR(255),
    "contact" VARCHAR(255),
    "status" VARCHAR(50) DEFAULT 'active', -- active / suspended / expired
    "plan_id" INTEGER REFERENCES "plan"("id") ON DELETE SET NULL,
    "title" VARCHAR(255),
    "favicon" VARCHAR(255),
    "banner_home" VARCHAR(255),
    "logo" VARCHAR(255),
    "theme_json" JSONB,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS "tenant_request" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "client_id" VARCHAR(255) UNIQUE NOT NULL,
    "client_url" VARCHAR(255),
    "name" VARCHAR(255),
    "email" VARCHAR(255),
    "contact" VARCHAR(255),
    "status" VARCHAR(50) DEFAULT 'pending', -- pending / approved / rejected
    "title" VARCHAR(255),
    "favicon" VARCHAR(255),
    "banner_home" VARCHAR(255),
    "logo" VARCHAR(255),
    "contact_name" VARCHAR(255),
    "contact_designation" VARCHAR(255),
    "address" VARCHAR(255),
    "city" VARCHAR(255),
    "district_id" INTEGER,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_request_district" FOREIGN KEY ("district_id") REFERENCES "core_district"("id") ON DELETE CASCADE
);


-- Notifications for tenant
CREATE TABLE IF NOT EXISTS "tenant_notifications" (
    "id" SERIAL PRIMARY KEY,
    "tenant_id" INT NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "title" VARCHAR(255),
    "message" TEXT,
    "type" VARCHAR(50), -- info / alert / warning
    "is_read" BOOLEAN DEFAULT FALSE,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Audit Logs (Superadmin Activity Tracking)
CREATE TABLE IF NOT EXISTS "tenant_audit_log" (
    "id" SERIAL PRIMARY KEY,
    "tenant_id" INT NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "action_type" VARCHAR(100), -- plan_change / branding_update / suspended
    "performed_by" VARCHAR(255),
    "description" TEXT,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Usage Tracking (e.g., SMS, Storage, API)
CREATE TABLE IF NOT EXISTS "tenant_usage" (
    "id" SERIAL PRIMARY KEY,
    "tenant_id" INT NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "metric_key" VARCHAR(100), -- sms_sent / storage_used / api_calls
    "metric_value" BIGINT DEFAULT 0,
    "recorded_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Webhook Integrations
CREATE TABLE IF NOT EXISTS "tenant_webhooks" (
    "id" SERIAL PRIMARY KEY,
    "tenant_id" INT NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "event_type" VARCHAR(100), -- payment_success / plan_upgrade
    "target_url" TEXT NOT NULL,
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Subscription Payment History Table: Tracks payment history for subscriptions
CREATE TABLE IF NOT EXISTS "subscription_payment_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "payment_id" VARCHAR(255) NOT NULL,
    "invoice_id" VARCHAR(255) NOT NULL,
    "plan_id" INTEGER NOT NULL,
    "created_by" VARCHAR(255) DEFAULT NULL,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255) DEFAULT NULL,
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("plan_id") REFERENCES "plan"("id") ON DELETE CASCADE
);

-- Coupons Table: Defines discount coupons
CREATE TABLE IF NOT EXISTS "coupons" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "name" VARCHAR(100) NOT NULL,
    "code" VARCHAR(255) NOT NULL,
    "discount" BIGINT NOT NULL,
    "discount_type" VARCHAR(255) NOT NULL,
    "start_date" TIMESTAMP NOT NULL,
    "end_date" TIMESTAMP NOT NULL,
    "min_order_amount" BIGINT DEFAULT 0,
    "max_discount" BIGINT DEFAULT 0,
    "limit_per_user" INTEGER NOT NULL,
    "image" VARCHAR(255),
    "description" VARCHAR(500),
    "created_by" VARCHAR(255) DEFAULT NULL,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255) DEFAULT NULL,
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Offers Table: Defines promotional offers
CREATE TABLE IF NOT EXISTS "offers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "name" VARCHAR(100) NOT NULL,
    "code" VARCHAR(255) NOT NULL,
    "discount" BIGINT NOT NULL,
    "discount_type" VARCHAR(255) NOT NULL,
    "start_date" TIMESTAMP NOT NULL,
    "end_date" TIMESTAMP NOT NULL,
    "min_order_amount" BIGINT DEFAULT 0,
    "max_discount" BIGINT DEFAULT 0,
    "limit_per_user" INTEGER NOT NULL,
    "image" VARCHAR(255),
    "description" VARCHAR(500),
    "created_by" VARCHAR(255) DEFAULT NULL,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255) DEFAULT NULL,
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Offers Plan Table: Links offers to plans
CREATE TABLE IF NOT EXISTS "offers_plan" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "offers_id" INTEGER NOT NULL,
    "plan_id" INTEGER NOT NULL,
    "created_by" VARCHAR(255) DEFAULT NULL,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255) DEFAULT NULL,
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("offers_id") REFERENCES "offers"("id") ON DELETE CASCADE,
    FOREIGN KEY ("plan_id") REFERENCES "plan"("id") ON DELETE CASCADE
);

-- Sales Report Table: Tracks sales reports
CREATE TABLE IF NOT EXISTS "sales_report" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "subscription_id" INTEGER NOT NULL,
    "coupons_id" INTEGER,
    "total_amount" BIGINT NOT NULL,
    "payment_type" VARCHAR(255) NOT NULL,
    "payment_status" VARCHAR(255) NOT NULL,
    "created_by" VARCHAR(255) DEFAULT NULL,
    "created_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255) DEFAULT NULL,
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("subscription_id") REFERENCES "subscription_payment_history"("id") ON DELETE CASCADE,
    FOREIGN KEY ("coupons_id") REFERENCES "coupons"("id") ON DELETE SET NULL
);

-- Invoices (Billing)
CREATE TABLE IF NOT EXISTS "invoices" (
    "id" SERIAL PRIMARY KEY,
    "tenant_id" INT NOT NULL REFERENCES "tenant"("id") ON DELETE CASCADE,
    "invoice_id" VARCHAR(255) UNIQUE NOT NULL,
    "amount" BIGINT NOT NULL,
    "status" VARCHAR(50) NOT NULL, -- paid / unpaid / cancelled
    "invoice_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "due_date" TIMESTAMP,
    "pdf_url" TEXT
);