
# Production configuration with Zoho Vault integration
spring:
  profiles:
    active: production
    
  # Database configuration will be loaded from Zoho Vault
  datasource:
    url: ${spring.datasource.url}
    username: ${db.user}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

# Server configuration
server:
  port: ${spring.port:8080}

# Zoho Vault configuration
zoho:
  vault:
    enabled: true
    base-url: https://vault.zoho.com/api/json
    auth-token: ${ZOHO_VAULT_AUTH_TOKEN}
    secrets-path: ${ZOHO_VAULT_SECRETS_PATH:clinichub-prod}
    cache-timeout-minutes: 30
    max-retries: 3
    retry-delay-seconds: 2

# Logging configuration
logging:
  level:
    com.clinichub: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/clinichub/application.log
    max-size: 10MB
    max-history: 30
