
-- ############################################################
-- # Organized Tables with Improvements
-- ############################################################

-- ############################################################
-- # Product Catalog Module
-- ############################################################

-- Catalog Category: Product categories
CREATE TABLE IF NOT EXISTS "catalog_category" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "parent_id" INTEGER,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "catalog_category_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "catalog_category" ("id") ON DELETE SET NULL
);

-- Catalog Brand: Product brands
CREATE TABLE IF NOT EXISTS "catalog_brand" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "logo_url" VARCHAR(500),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Catalog Product Type: Types of products
CREATE TABLE IF NOT EXISTS "catalog_product_type" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Catalog Product: Products in the catalog
CREATE TABLE IF NOT EXISTS "catalog_product" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "category_id" INTEGER NOT NULL,
    "brand_id" INTEGER,
    "product_type_id" INTEGER,
    "sku" VARCHAR(50) NOT NULL,
    "price" DECIMAL(10,2) NOT NULL,
    "cost_price" DECIMAL(10,2),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "is_serialized" BOOLEAN NOT NULL DEFAULT false,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "catalog_product_category_fk" FOREIGN KEY ("category_id") REFERENCES "catalog_category" ("id") ON DELETE CASCADE,
    CONSTRAINT "catalog_product_brand_fk" FOREIGN KEY ("brand_id") REFERENCES "catalog_brand" ("id") ON DELETE SET NULL,
    CONSTRAINT "catalog_product_type_fk" FOREIGN KEY ("product_type_id") REFERENCES "catalog_product_type" ("id") ON DELETE SET NULL
);

-- Catalog Product Serial: Serial numbers for products
CREATE TABLE IF NOT EXISTS "catalog_product_serial" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INTEGER NOT NULL,
    "serial_number" VARCHAR(100) NOT NULL,
    "status" VARCHAR(50) NOT NULL DEFAULT 'Available',
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "product_serial_product_fk" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") ON DELETE CASCADE
);

-- Catalog Batch: Product batches
CREATE TABLE IF NOT EXISTS "catalog_batch" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INTEGER NOT NULL,
    "batch_number" VARCHAR(100) NOT NULL,
    "manufacturing_date" DATE,
    "expiry_date" DATE,
    "quantity" INTEGER NOT NULL DEFAULT 0,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "catalog_batch_product_fk" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") ON DELETE CASCADE
);

-- Catalog Stock Config: Stock configurations
CREATE TABLE IF NOT EXISTS "catalog_stock_config" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INTEGER,
    "min_stock_level" INTEGER NOT NULL DEFAULT 10,
    "max_stock_level" INTEGER,
    "reorder_point" INTEGER NOT NULL DEFAULT 20,
    "qty_min" VARCHAR(255),
    "exp_month" VARCHAR(255),
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "stock_config_product_fk" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") ON DELETE CASCADE
);

-- ############################################################
-- # Vendor Module
-- ############################################################

-- Vendor: Suppliers of products
CREATE TABLE IF NOT EXISTS "vendor" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "contact_person" VARCHAR(255),
    "email" VARCHAR(255),
    "phone" VARCHAR(50) NOT NULL,
    "address" VARCHAR(500),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Vendor PO Import Config: Import configurations
CREATE TABLE IF NOT EXISTS "vendor_po_import_config" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "vendor_id" INTEGER NOT NULL,
    "file_format" VARCHAR(50) NOT NULL,
    "column_mappings" JSONB NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "po_import_vendor_fk" FOREIGN KEY ("vendor_id") REFERENCES "vendor" ("id") ON DELETE CASCADE
);

-- ############################################################
-- # Purchase Module
-- ############################################################

-- Purchase Order: Orders to vendors
CREATE TABLE IF NOT EXISTS "purchase_order" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "vendor_id" INTEGER NOT NULL,
    "order_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "expected_delivery" DATE,
    "status" VARCHAR(50) DEFAULT 'Pending',
    "total_amount" DECIMAL(12,2) NOT NULL,
    "notes" TEXT,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "purchase_order_vendor_fk" FOREIGN KEY ("vendor_id") REFERENCES "vendor" ("id") ON DELETE CASCADE
);

-- Purchase Order Items: Items in vendor orders
CREATE TABLE IF NOT EXISTS "purchase_order_items" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "purchase_order_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_price" DECIMAL(10,2) NOT NULL,
    "total_price" DECIMAL(10,2) NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "po_items_order_fk" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_order" ("id") ON DELETE CASCADE,
    CONSTRAINT "po_items_product_fk" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") ON DELETE CASCADE
);

-- Purchase Order Item Serial: Serial items in orders
CREATE TABLE IF NOT EXISTS "purchase_order_item_serial" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "purchase_order_item_id" INTEGER NOT NULL,
    "serial_number" VARCHAR(100) NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "po_item_serial_item_fk" FOREIGN KEY ("purchase_order_item_id") REFERENCES "purchase_order_items" ("id") ON DELETE CASCADE
);

-- ############################################################
-- # Sales Module
-- ############################################################

-- Address Type: Types of addresses
CREATE TABLE IF NOT EXISTS "address_type" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(50) NOT NULL,
    "description" VARCHAR(255),
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Shipment Type: Types of shipment methods
CREATE TABLE IF NOT EXISTS "shipment_type" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Courier: Shipping couriers
CREATE TABLE IF NOT EXISTS "courier" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "contact_number" VARCHAR(50),
    "website" VARCHAR(255),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "sales_order" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"uid" VARCHAR(50) NULL DEFAULT NULL,
	"branch_id" BIGINT NULL DEFAULT NULL,
	"customer_id" BIGINT NULL DEFAULT NULL,
	"payment_type_id" BIGINT NULL DEFAULT NULL,
	"subtotal" NUMERIC(20,2) NULL DEFAULT NULL,
	"discount_value" NUMERIC(20,2) NULL DEFAULT NULL,
	"discount_type" VARCHAR(50) NULL DEFAULT NULL,
	"discount" NUMERIC(20,2) NULL DEFAULT NULL,
	"grand_total" NUMERIC(20,2) NULL DEFAULT NULL,
	"paid_amount" NUMERIC(20,2) NULL DEFAULT NULL,
	"balance" NUMERIC(20,2) NULL DEFAULT NULL,
	"remark" VARCHAR(255) NULL DEFAULT NULL,
	"is_approved" BOOLEAN NOT NULL DEFAULT false,
	"approved_by" VARCHAR(50) NULL DEFAULT NULL,
	"approved_time" TIMESTAMP NULL DEFAULT NULL,
	"created_by" VARCHAR(50) NOT NULL,
	"created_time" TIMESTAMP NOT NULL,
	"modified_by" VARCHAR(50) NULL DEFAULT NULL,
	"modified_time" TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "sales_order_branch_fk" FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT "sales_order_customer_fk" FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT "sales_order_payment_type_fk" FOREIGN KEY ("payment_type_id") REFERENCES "payment_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- Sales Order Items: Items in customer orders
CREATE TABLE IF NOT EXISTS "sales_order_items" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "sales_order_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_price" DECIMAL(10,2) NOT NULL,
    "total_price" DECIMAL(10,2) NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "sales_item_order_fk" FOREIGN KEY ("sales_order_id") REFERENCES "sales_order" ("id") ON DELETE CASCADE,
    CONSTRAINT "sales_item_product_fk" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") ON DELETE CASCADE
);

-- Sales Order Item Serial: Serial items in sales
CREATE TABLE IF NOT EXISTS "sales_order_item_serial" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "sales_order_item_id" INTEGER NOT NULL,
    "serial_number" VARCHAR(100) NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "sales_item_serial_item_fk" FOREIGN KEY ("sales_order_item_id") REFERENCES "sales_order_items" ("id") ON DELETE CASCADE
);

-- ############################################################
-- # Appointment Module
-- ############################################################

-- Slot Types: Types of appointment slots
CREATE TABLE IF NOT EXISTS "slot_types" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "duration_minutes" INTEGER NOT NULL DEFAULT 30,
    "color_code" VARCHAR(20),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Slot: Available appointment slots
CREATE TABLE IF NOT EXISTS "slot" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "slot_type_id" INTEGER NOT NULL,
    "start_time" TIMESTAMP NOT NULL,
    "end_time" TIMESTAMP NOT NULL,
    "is_available" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "slot_type_fk" FOREIGN KEY ("slot_type_id") REFERENCES "slot_types" ("id") ON DELETE CASCADE
);

-- Slot Therapist: Therapists available for slots
CREATE TABLE IF NOT EXISTS "slot_therapiest" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "slot_id" INTEGER NOT NULL,
    "therapist_id" INTEGER NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "slot_therapist_slot_fk" FOREIGN KEY ("slot_id") REFERENCES "slot" ("id") ON DELETE CASCADE,
    CONSTRAINT "slot_therapist_doctor_fk" FOREIGN KEY ("therapist_id") REFERENCES "doctor" ("id") ON DELETE CASCADE
);


-- ############################################################
-- # Repair Module
-- ############################################################

-- Repair Company: Companies for repairs
CREATE TABLE IF NOT EXISTS "repair_company" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "contact_person" VARCHAR(255),
    "email" VARCHAR(255),
    "phone" VARCHAR(50) NOT NULL,
    "address" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Repair Status: Repair status options
CREATE TABLE IF NOT EXISTS "repair_status" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "color_code" VARCHAR(20),
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Repair Condition: Condition of repair items
CREATE TABLE IF NOT EXISTS "repair_condition" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Repair Defect: Types of defects
CREATE TABLE IF NOT EXISTS "repair_defect" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Repair Service: Types of repair services
CREATE TABLE IF NOT EXISTS "repair_service" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "price" DECIMAL(10,2) NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Repair Fit: Fit types for repaired items
CREATE TABLE IF NOT EXISTS "repair_fit" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Repair Speaker: Speakers for repair items
CREATE TABLE IF NOT EXISTS "repair_speaker" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Repair Courier: Shipping for repairs
CREATE TABLE IF NOT EXISTS "repair_courier" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "contact_number" VARCHAR(50),
    "website" VARCHAR(255),
    "tracking_url_pattern" VARCHAR(500),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Repair Address: Addresses for repairs
CREATE TABLE IF NOT EXISTS "repair_address" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "address_line1" VARCHAR(255) NOT NULL,
    "address_line2" VARCHAR(255),
    "city" VARCHAR(100) NOT NULL,
    "district_id" INTEGER NOT NULL,
    "postal_code" VARCHAR(20) NOT NULL,
    "contact_person" VARCHAR(255) NOT NULL,
    "contact_phone" VARCHAR(50) NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "repair_address_district_fk" FOREIGN KEY ("district_id") REFERENCES "core_district" ("id") ON DELETE CASCADE
);

-- Repair Transaction: Repair transactions
CREATE TABLE IF NOT EXISTS "repair_transaction" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "customer_id" INTEGER NOT NULL,
    "company_id" INTEGER,
    "transaction_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "status_id" INTEGER NOT NULL,
    "total_amount" DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    "notes" TEXT,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "repair_transaction_customer_fk" FOREIGN KEY ("customer_id") REFERENCES "patient" ("id") ON DELETE CASCADE,
    CONSTRAINT "repair_transaction_company_fk" FOREIGN KEY ("company_id") REFERENCES "repair_company" ("id") ON DELETE SET NULL,
    CONSTRAINT "repair_transaction_status_fk" FOREIGN KEY ("status_id") REFERENCES "repair_status" ("id") ON DELETE CASCADE
);

-- Repair Product Info: Repair item details
CREATE TABLE IF NOT EXISTS "repair_productinfo" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "repair_id" INTEGER NOT NULL,
    "product_name" VARCHAR(255) NOT NULL,
    "serial_number" VARCHAR(100),
    "purchase_date" DATE,
    "condition_id" INTEGER,
    "defect_id" INTEGER,
    "defect_description" TEXT,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "repair_productinfo_repair_fk" FOREIGN KEY ("repair_id") REFERENCES "repair_transaction" ("id") ON DELETE CASCADE,
    CONSTRAINT "repair_productinfo_condition_fk" FOREIGN KEY ("condition_id") REFERENCES "repair_condition" ("id") ON DELETE SET NULL,
    CONSTRAINT "repair_productinfo_defect_fk" FOREIGN KEY ("defect_id") REFERENCES "repair_defect" ("id") ON DELETE SET NULL
);

-- Repair: Repair records
CREATE TABLE IF NOT EXISTS "repair" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "transaction_id" INTEGER NOT NULL,
    "product_info_id" INTEGER NOT NULL,
    "service_id" INTEGER NOT NULL,
    "price" DECIMAL(10,2) NOT NULL,
    "fit_id" INTEGER,
    "speaker_id" INTEGER,
    "notes" TEXT,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "repair_transaction_fk" FOREIGN KEY ("transaction_id") REFERENCES "repair_transaction" ("id") ON DELETE CASCADE,
    CONSTRAINT "repair_product_info_fk" FOREIGN KEY ("product_info_id") REFERENCES "repair_productinfo" ("id") ON DELETE CASCADE,
    CONSTRAINT "repair_service_fk" FOREIGN KEY ("service_id") REFERENCES "repair_service" ("id") ON DELETE CASCADE,
    CONSTRAINT "repair_fit_fk" FOREIGN KEY ("fit_id") REFERENCES "repair_fit" ("id") ON DELETE SET NULL,
    CONSTRAINT "repair_speaker_fk" FOREIGN KEY ("speaker_id") REFERENCES "repair_speaker" ("id") ON DELETE SET NULL
);

-- Repair Payment: Payment for repairs
CREATE TABLE IF NOT EXISTS "repair_payment" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "repair_transaction_id" INTEGER NOT NULL,
    "payment_type_id" INTEGER NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "payment_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "reference_number" VARCHAR(100),
    "notes" TEXT,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "repair_payment_transaction_fk" FOREIGN KEY ("repair_transaction_id") REFERENCES "repair_transaction" ("id") ON DELETE CASCADE,
    CONSTRAINT "repair_payment_type_fk" FOREIGN KEY ("payment_type_id") REFERENCES "payment_type" ("id") ON DELETE CASCADE
);

-- Repair Problem Data: Additional repair details
CREATE TABLE IF NOT EXISTS "repair_problem_data" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "repair_id" INTEGER ,
    "problem_key" VARCHAR(100) ,
    "type" VARCHAR(100),
    "name" VARCHAR(100),
    "problem_value" TEXT,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "repair_problem_data_repair_fk" FOREIGN KEY ("repair_id") REFERENCES "repair" ("id") ON DELETE CASCADE
);

-- Repair Response: Responses from repair company
CREATE TABLE IF NOT EXISTS "repair_response" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "repair_transaction_id" INTEGER NOT NULL,
    "response_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "response_details" TEXT NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "repair_response_transaction_fk" FOREIGN KEY ("repair_transaction_id") REFERENCES "repair_transaction" ("id") ON DELETE CASCADE
);

-- Repair Test Delivery: Delivery test for repairs
CREATE TABLE IF NOT EXISTS "repair_test_delivery" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "repair_transaction_id" INTEGER NOT NULL,
    "courier_id" INTEGER NOT NULL,
    "tracking_number" VARCHAR(100),
    "shipping_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "delivery_status" VARCHAR(50) DEFAULT 'Shipped',
    "notes" TEXT,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "test_delivery_transaction_fk" FOREIGN KEY ("repair_transaction_id") REFERENCES "repair_transaction" ("id") ON DELETE CASCADE,
    CONSTRAINT "test_delivery_courier_fk" FOREIGN KEY ("courier_id") REFERENCES "repair_courier" ("id") ON DELETE CASCADE
);

-- ############################################################
-- # OT Module (Operation Theater)
-- ############################################################

-- OT Category: Operation theater categories
CREATE TABLE IF NOT EXISTS "ot_category" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- OT Subcategory: Subcategories in operation theater
CREATE TABLE IF NOT EXISTS "ot_subcategory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "category_id" INTEGER NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "ot_subcategory_category_fk" FOREIGN KEY ("category_id") REFERENCES "ot_category" ("id") ON DELETE CASCADE
);

-- OT Checklist: Operation theater checklists
CREATE TABLE IF NOT EXISTS "ot_checklist" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "category_id" INTEGER NOT NULL,
    "subcategory_id" INTEGER,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "is_mandatory" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "ot_checklist_category_fk" FOREIGN KEY ("category_id") REFERENCES "ot_category" ("id") ON DELETE CASCADE,
    CONSTRAINT "ot_checklist_subcategory_fk" FOREIGN KEY ("subcategory_id") REFERENCES "ot_subcategory" ("id") ON DELETE SET NULL
);

-- OT Children: Operation theater procedures
CREATE TABLE IF NOT EXISTS "ot_children" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- OT Children Checklist Map: Mapping between procedures and checklists
CREATE TABLE IF NOT EXISTS "ot_children_checklist_map" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "children_id" INTEGER NOT NULL,
    "checklist_id" INTEGER NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "ot_children_checklist_map_children_fk" FOREIGN KEY ("children_id") REFERENCES "ot_children" ("id") ON DELETE CASCADE,
    CONSTRAINT "ot_children_checklist_map_checklist_fk" FOREIGN KEY ("checklist_id") REFERENCES "ot_checklist" ("id") ON DELETE CASCADE
);

-- OT IDP: Interdisciplinary plans
CREATE TABLE IF NOT EXISTS "ot_children_idp" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- OT IDP Checklist Map: Mapping between IDPs and checklists
CREATE TABLE IF NOT EXISTS "ot_idp_checklist_map" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "idp_id" INTEGER NOT NULL,
    "checklist_id" INTEGER NOT NULL,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "ot_idp_checklist_map_idp_fk" FOREIGN KEY ("idp_id") REFERENCES "ot_children_idp" ("id") ON DELETE CASCADE,
    CONSTRAINT "ot_idp_checklist_map_checklist_fk" FOREIGN KEY ("checklist_id") REFERENCES "ot_checklist" ("id") ON DELETE CASCADE
);

-- ############################################################
-- # Website Module
-- ############################################################

-- Website Slider: Slider images for website
CREATE TABLE IF NOT EXISTS "website_slider" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "subtitle" VARCHAR(500),
    "image_url" VARCHAR(500) NOT NULL,
    "link_url" VARCHAR(500),
    "sequence" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- ############################################################
-- # Prescription Module
-- ############################################################

-- Prescription Medicines: Medicines in prescriptions
CREATE TABLE IF NOT EXISTS "visit_medicines" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
   "visit_id" INTEGER NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "dosage" VARCHAR(100) NOT NULL,
    "frequency" VARCHAR(100) NOT NULL,
    "timings" VARCHAR(100) NOT NULL,
    "duration" VARCHAR(100) NOT NULL,
    "instructions" TEXT,
    "created_by" VARCHAR(255) NOT NULL,
    "created_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" VARCHAR(255),
    "modified_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "visit_medicines_visit_id" FOREIGN KEY ("visit_id") REFERENCES "patient_schedule" ("id") ON DELETE CASCADE
);