DROP VIEW IF EXISTS "doctor_clinic_map_view";  

ALTER TABLE clinic
  ALTER COLUMN email TYPE VARCHAR(100),
  ALTER COLUMN contact TYPE VARCHAR(15),
  ALTER COLUMN alternate_phone TYPE VARCHAR(15),
  ALTER COLUMN emergency_contact TYPE VARCHAR(15),
  ALTER COLUMN address TYPE VARCHAR(300),
  ALTER COLUMN gst TYPE VARCHAR(100),
  ALTER COLUMN pan TYPE VARCHAR(20),
  ALTER COLUMN owner_name TYPE VARCHAR(100),
  ALTER COLUMN license_number TYPE VARCHAR(100),
  ALTER COLUMN license_authority TYPE VARCHAR(100);
  
