import { AllAppointment, Appointment } from "../types/Appointment";
import { Patient } from "../../patients/types/Patient";
import { Doctor } from "../../doctor/types/Doctor";
import { Slot } from "../types/Slot";
import { Branch } from "../../shared/types/Branch";
import { DoctorClinic } from "../types/DoctorClinic";
import { User } from "../../users/types/User";

const mockAppointments: AllAppointment[] = [
  {
    id: 1,
    appointmentDate: new Date(),
    status: "upcoming",
    branch: {
      id: 1,
      name: "Main Branch",
      code: "MB-001",
      location: "Downtown",
      active: true,
      state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
      district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
      country: { id: 1, name: "United States", code: "US" },
      city: "New York",
      mapUrl: "",
      pincode: 10001,
      image: "",
      latitude: 40.7128,
      longitude: -74.0060,
    },
    patient: {
      id: 1,
      uid: "PT-001",
      gender: "Male",
      dob: new Date(),
      city: "New York",
      age: 30,
      address: "123 Main St",
      firstname: "John",
      lastname: "Doe",
      user: {
        id: 1,
        name: "John Doe",
        username: "johndoe",
        email: "john.doe@example.com",
        phone: "123-456-7890",
        password: "password",
        branch: {
          id: 1,
          name: "Main Branch",
          code: "MB-001",
          location: "Downtown",
          active: true,
          state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
          district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
          country: { id: 1, name: "United States", code: "US" },
          city: "New York",
          mapUrl: "",
          pincode: 10001,
          image: "",
          latitude: 40.7128,
          longitude: -74.0060,
        },
        role: { id: 1, name: "Admin", permissions: [] },
        image: ""
      },
      branch: {
        id: 1,
        name: "Main Branch",
        code: "MB-001",
        location: "Downtown",
        active: true,
        state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
        district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
        country: { id: 1, name: "United States", code: "US" },
        city: "New York",
        mapUrl: "",
        pincode: 10001,
        image: "",
        latitude: 40.7128,
        longitude: -74.0060,
      },
      refDoctor: {
        id: 1,
        uid: "DR-001",
        firstname: "John",
        lastname: "Smith",
        email: "john.smith@example.com",
        desgination: "Cardiologist",
        specializationList: [],
        qualification: "MD",
        joiningDate: new Date(),
        user: {
          id: 1,
          name: "John Smith",
          username: "johnsmith",
          email: "john.smith@example.com",
          phone: "123-456-7890",
          password: "password",
          branch: {
            id: 1,
            name: "Main Branch",
            code: "MB-001",
            location: "Downtown",
            active: true,
            state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
            district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
            country: { id: 1, name: "United States", code: "US" },
            city: "New York",
            mapUrl: "",
            pincode: 10001,
            image: "",
            latitude: 40.7128,
            longitude: -74.0060,
          },
          role: { id: 1, name: "Admin", permissions: [] },
          image: ""
        },
        external: false,
        external_temp: null
      }
    },
    doctor: {
      id: 1,
      uid: "DR-001",
      firstname: "John",
      lastname: "Smith",
      email: "john.smith@example.com",
      desgination: "Cardiologist",
      specializationList: [],
      qualification: "MD",
      joiningDate: new Date(),
      user: {
        id: 1,
        name: "John Smith",
        username: "johnsmith",
        email: "john.smith@example.com",
        phone: "123-456-7890",
        password: "password",
        branch: {
          id: 1,
          name: "Main Branch",
          code: "MB-001",
          location: "Downtown",
          active: true,
          state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
          district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
          country: { id: 1, name: "United States", code: "US" },
          city: "New York",
          mapUrl: "",
          pincode: 10001,
          image: "",
          latitude: 40.7128,
          longitude: -74.0060,
        },
        role: { id: 1, name: "Admin", permissions: [] },
        image: ""
      },
      external: false,
      external_temp: null
    },
    slot: { id: 1, availableSlots: 2 },
    familyMember: { id: "1", name: "Jane Doe", age: 28, gender: "Female", phone: "987-654-3210", relationship: "Wife" },
    doctorClinic: {
      id: 1,
      doctor: {
        id: 1,
        uid: "DR-001",
        firstname: "John",
        lastname: "Smith",
        email: "john.smith@example.com",
        desgination: "Cardiologist",
        specializationList: [],
        qualification: "MD",
        joiningDate: new Date(),
        user: {
          id: 1,
          name: "John Smith",
          username: "johnsmith",
          email: "john.smith@example.com",
          phone: "123-456-7890",
          password: "password",
          branch: {
            id: 1,
            name: "Main Branch",
            code: "MB-001",
            location: "Downtown",
            active: true,
            state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
            district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
            country: { id: 1, name: "United States", code: "US" },
            city: "New York",
            mapUrl: "",
            pincode: 10001,
            image: "",
            latitude: 40.7128,
            longitude: -74.0060,
          },
          role: { id: 1, name: "Admin", permissions: [] },
          image: ""
        },
        external: false,
        external_temp: null
      },
      clinic: {
        id: 1,
        uid: "CL-001",
        name: "Main Clinic",
        email: "main.clinic@example.com",
        contact: "123-456-7890",
        address: "123 Main St",
        plan: { features: { id: 1, module: { id: 1, name: "Cardiology" }, print: true } }
      }
    },
    isAccept: true
  },
  {
    id: 2,
    appointmentDate: new Date(),
    status: "completed",
    branch: {
      id: 1,
      name: "Main Branch",
      code: "MB-001",
      location: "Downtown",
      active: true,
      state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
      district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
      country: { id: 1, name: "United States", code: "US" },
      city: "New York",
      mapUrl: "",
      pincode: 10001,
      image: "",
      latitude: 40.7128,
      longitude: -74.0060,
    },
    patient: {
      id: 2,
      uid: "PT-002",
      gender: "Female",
      dob: new Date(),
      city: "Los Angeles",
      age: 40,
      address: "456 Elm St",
      firstname: "Jane",
      lastname: "Smith",
      user: {
        id: 2,
        name: "Jane Smith",
        username: "janesmith",
        email: "jane.smith@example.com",
        phone: "987-654-3210",
        password: "password",
        branch: {
          id: 1,
          name: "Main Branch",
          code: "MB-001",
          location: "Downtown",
          active: true,
          state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
          district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
          country: { id: 1, name: "United States", code: "US" },
          city: "New York",
          mapUrl: "",
          pincode: 10001,
          image: "",
          latitude: 40.7128,
          longitude: -74.0060,
        },
        role: { id: 1, name: "Admin", permissions: [] },
        image: ""
      },
      branch: {
        id: 1,
        name: "Main Branch",
        code: "MB-001",
        location: "Downtown",
        active: true,
        state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
        district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
        country: { id: 1, name: "United States", code: "US" },
        city: "New York",
        mapUrl: "",
        pincode: 10001,
        image: "",
        latitude: 40.7128,
        longitude: -74.0060,
      },
      refDoctor: {
        id: 1,
        uid: "DR-001",
        firstname: "John",
        lastname: "Smith",
        email: "john.smith@example.com",
        desgination: "Cardiologist",
        specializationList: [],
        qualification: "MD",
        joiningDate: new Date(),
        user: {
          id: 1,
          name: "John Smith",
          username: "johnsmith",
          email: "john.smith@example.com",
          phone: "123-456-7890",
          password: "password",
          branch: {
            id: 1,
            name: "Main Branch",
            code: "MB-001",
            location: "Downtown",
            active: true,
            state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
            district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
            country: { id: 1, name: "United States", code: "US" },
            city: "New York",
            mapUrl: "",
            pincode: 10001,
            image: "",
            latitude: 40.7128,
            longitude: -74.0060,
          },
          role: { id: 1, name: "Admin", permissions: [] },
          image: ""
        },
        external: false,
        external_temp: null
      }
    },
    doctor: {
      id: 1,
      uid: "DR-001",
      firstname: "John",
      lastname: "Smith",
      email: "john.smith@example.com",
      desgination: "Cardiologist",
      specializationList: [],
      qualification: "MD",
      joiningDate: new Date(),
      user: {
        id: 1,
        name: "John Smith",
        username: "johnsmith",
        email: "john.smith@example.com",
        phone: "123-456-7890",
        password: "password",
        branch: {
          id: 1,
          name: "Main Branch",
          code: "MB-001",
          location: "Downtown",
          active: true,
          state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
          district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
          country: { id: 1, name: "United States", code: "US" },
          city: "New York",
          mapUrl: "",
          pincode: 10001,
          image: "",
          latitude: 40.7128,
          longitude: -74.0060,
        },
        role: { id: 1, name: "Admin", permissions: [] },
        image: ""
      },
      external: false,
      external_temp: null
    },
    slot: { id: 2, availableSlots: 0 },
    familyMember: { id: "2", name: "Tom Smith", age: 10, gender: "Male", phone: "987-654-3210", relationship: "Son" },
    doctorClinic: {
      id: 1,
      doctor: {
        id: 1,
        uid: "DR-001",
        firstname: "John",
        lastname: "Smith",
        email: "john.smith@example.com",
        desgination: "Cardiologist",
        specializationList: [],
        qualification: "MD",
        joiningDate: new Date(),
        user: {
          id: 1,
          name: "John Smith",
          username: "johnsmith",
          email: "john.smith@example.com",
          phone: "123-456-7890",
          password: "password",
          branch: {
            id: 1,
            name: "Main Branch",
            code: "MB-001",
            location: "Downtown",
            active: true,
            state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } },
            district: { id: 1, name: "Manhattan", state: { id: 1, name: "New York", country: { id: 1, name: "United States", code: "US" } } },
            country: { id: 1, name: "United States", code: "US" },
            city: "New York",
            mapUrl: "",
            pincode: 10001,
            image: "",
            latitude: 40.7128,
            longitude: -74.0060,
          },
          role: { id: 1, name: "Admin", permissions: [] },
          image: ""
        },
        external: false,
        external_temp: null
      },
      clinic: {
        id: 1,
        uid: "CL-001",
        name: "Main Clinic",
        email: "main.clinic@example.com",
        contact: "123-456-7890",
        address: "123 Main St",
        plan: { features: { id: 1, module: { id: 1, name: "Cardiology" }, print: true } }
      }
    },
    isAccept: true
  },
];

export const findAllAppointments = () => {
  return mockAppointments;
};

export const findAppointmentById = (id: number) => {
  return mockAppointments.find((appointment) => appointment.id === id);
};

export default { findAllAppointments, findAppointmentById };
