CREATE TABLE IF NOT EXISTS "clinic_review" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"massage" VARCHAR(500) NOT NULL DEFAULT NULL,
	"rating" DOUBLE PRECISION,
	"branch_id" INTEGER,
	"patient_id" INTEGER,
	"clinic_id" INTEGER,
	"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
	"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
	"modified_by" VARCHAR(255) NULL DEFAULT NULL,
	"modified_time" TIMESTAMP NULL DEFAULT NULL,
	 FOREIGN KEY (patient_id) REFERENCES Patient ( id ),
	 FOREIGN KEY (branch_id) REFERENCES Branch ( id ),
	 FOREIGN KEY (clinic_id) REFERENCES Clinic ( id ),
	 PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "clinic_service" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"service_id" INTEGER,
	"branch_id" INTEGER,
	"clinic_id" INTEGER,
	"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
	"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
	"modified_by" VARCHAR(255) NULL DEFAULT NULL,
	"modified_time" TIMESTAMP NULL DEFAULT NULL,
	 FOREIGN KEY (service_id) REFERENCES Service_type ( id ),
	 FOREIGN KEY (branch_id) REFERENCES Branch ( id ),
	 FOREIGN KEY (clinic_id) REFERENCES Clinic ( id ),
	 PRIMARY KEY ("id")
);
