
CREATE TABLE IF NOT EXISTS doctor_availability (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
doctor_id INTEGER NOT NULL,
branch_id INTEGER NOT NULL,
day_of_week VARCHAR(10) CHECK (day_of_week IN (
       'Sunday','Monday','Tuesday',
		 'Wednesday','Thursday','Friday','Saturday'
    )),
start_time TIME NOT NULL,
end_time TIME NOT NULL,
slot_duration INTEGER DEFAULT 15,
active BOOLEAN DEFAULT TRUE,
"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
"modified_by" VARCHAR(255) NULL DEFAULT NULL,
"modified_time" TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY ("id") ,
FOREIGN KEY (doctor_id) REFERENCES Doctor ( id ),
FOREIGN KEY (branch_id) REFERENCES Branch ( id )
);

CREATE TABLE IF NOT EXISTS doctor_schedule_break (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
doctor_id INTEGER NOT NULL,
branch_id INTEGER NOT NULL,
day_of_week VARCHAR(10) CHECK (day_of_week IN (
       'Sunday','Monday','Tuesday',
		 'Wednesday','Thursday','Friday','Saturday'
    )),
break_start TIME NOT NULL,
break_end TIME NOT NULL,
description VARCHAR(255),
"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
"modified_by" VARCHAR(255) NULL DEFAULT NULL,
"modified_time" TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY ("id") ,
 FOREIGN KEY (doctor_id) REFERENCES Doctor ( id ),
 FOREIGN KEY (branch_id) REFERENCES Branch ( id )
);


CREATE TABLE IF NOT EXISTS doctor_leave (
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
doctor_id INTEGER NOT NULL,
branch_id INTEGER NOT NULL,
leave_start DATE NOT NULL,
leave_end DATE NOT NULL,
reason VARCHAR(255),
approved BOOLEAN DEFAULT TRUE,
"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
"modified_by" VARCHAR(255) NULL DEFAULT NULL,
"modified_time" TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (id),
FOREIGN KEY (doctor_id) REFERENCES Doctor ( id ),
FOREIGN KEY (branch_id) REFERENCES Branch ( id )
);



CREATE TABLE IF NOT EXISTS blocked_slot (
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
doctor_id INTEGER NOT NULL,
slot_date DATE NOT NULL,
start_time TIME NOT NULL,
end_time TIME NOT NULL,
reason VARCHAR(255),
"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
"modified_by" VARCHAR(255) NULL DEFAULT NULL,
"modified_time" TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (id),
FOREIGN KEY (doctor_id) REFERENCES Doctor ( id )
);



CREATE TABLE IF NOT EXISTS clinic_holidday (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
"branch_id" INTEGER NOT NULL,
"date" DATE NOT NULL,
"reason" VARCHAR(255),
"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
"modified_by" VARCHAR(255) NULL DEFAULT NULL,
"modified_time" TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (id),
FOREIGN KEY (branch_id) REFERENCES Branch ( id )
);
 