ALTER TABLE patient ADD COLUMN IF NOT EXISTS global_patient_id UUID;

ALTER TABLE doctor_branch ADD COLUMN IF NOT EXISTS global_doctor_branch_id UUID;


ALTER TABLE doctor_slot ADD COLUMN IF NOT EXISTS global_slot_id UUID;


CREATE TABLE IF NOT EXISTS "clinic_facility" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR (200), 
	"created_by" VARCHAR(255) NOT NULL DEFAULT NULL,
	"created_time" TIMESTAMP NOT NULL DEFAULT NULL,
	"modified_by" VARCHAR(255) NULL DEFAULT NULL,
	"modified_time" TIMESTAMP NULL DEFAULT NULL,	 
	 PRIMARY KEY("id")
);
 

 ALTER TABLE "clinic"
ADD COLUMN gst VARCHAR( 255),
ADD COLUMN pan VARCHAR (250),
ADD COLUMN owner_name VARCHAR (200);
 

 CREATE TABLE IF NOT EXISTS "clinic_facility_map" (
    "clinic_id" BIGINT NOT NULL,
    "facility_id" BIGINT NOT NULL,
    PRIMARY KEY ("clinic_id", "facility_id"),
    CONSTRAINT "fk_clinic" FOREIGN KEY ("clinic_id") REFERENCES clinic ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_facility" FOREIGN KEY ("facility_id") REFERENCES  clinic_facility ("id") ON DELETE CASCADE

);

 