ALTER TABLE clinic
ADD COLUMN IF NOT EXISTS description VARCHAR(300),
ADD COLUMN IF NOT EXISTS tagline VARCHAR(300),
ADD COLUMN IF NOT EXISTS established_year VARCHAR(10), 
ADD COLUMN IF NOT EXISTS website VARCHAR(300),
ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(15),
ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(15),
ADD COLUMN IF NOT EXISTS license_number VARCHAR(300),
ADD COLUMN IF NOT EXISTS license_authority VARCHAR(300);