ALTER TABLE clinic ADD COLUMN IF NOT EXISTS exist_software VARCHAR(255),
ADD COLUMN IF NOT EXISTS accept_terms BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS consent_to_contact BOOLEAN NOT NULL DEFAULT FALSE;

