
-- Laboratory Test Reporting System
-- Migration to create comprehensive test management tables

-- Test Categories Table
CREATE TABLE IF NOT EXISTS test_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(255),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255),
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Test Types Table  
CREATE TABLE IF NOT EXISTS test_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(50) UNIQUE,
    description TEXT,
    sample_type VARCHAR(100),
    preparation_instructions TEXT,
    turnaround_time_hours INTEGER DEFAULT 24,
    active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(255),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255),
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_test_types_category FOREIGN KEY (category_id) REFERENCES test_categories(id) ON DELETE CASCADE
);

-- Test Parameters Table
CREATE TABLE IF NOT EXISTS test_parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_type_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(50),
    unit VARCHAR(50),
    reference_min NUMERIC(15,4),
    reference_max NUMERIC(15,4),
    reference_text VARCHAR(500),
    parameter_type VARCHAR(50) DEFAULT 'NUMERIC', -- NUMERIC, TEXT, BOOLEAN, RANGE
    display_order INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(255),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255),
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_test_parameters_type FOREIGN KEY (test_type_id) REFERENCES test_types(id) ON DELETE CASCADE
);

-- Test Reports Table (links to existing patient table)
CREATE TABLE IF NOT EXISTS test_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    test_type_id BIGINT NOT NULL,
    report_number VARCHAR(100) UNIQUE NOT NULL,
    report_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    collection_date TIMESTAMP,
    received_date TIMESTAMP,
    reported_date TIMESTAMP,
    status VARCHAR(50) DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED, CANCELLED
    priority VARCHAR(20) DEFAULT 'ROUTINE', -- URGENT, ROUTINE, STAT
    referring_doctor VARCHAR(200),
    clinical_history TEXT,
    diagnosis TEXT,
    comments TEXT,
    technician_name VARCHAR(200),
    pathologist_name VARCHAR(200),
    verified_by VARCHAR(200),
    verified_date TIMESTAMP,
    active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(255),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255),
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_test_reports_patient FOREIGN KEY (patient_id) REFERENCES patient(id) ON DELETE CASCADE,
    CONSTRAINT fk_test_reports_test_type FOREIGN KEY (test_type_id) REFERENCES test_types(id) ON DELETE CASCADE
);

-- Test Results Table
CREATE TABLE IF NOT EXISTS test_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_report_id BIGINT NOT NULL,
    test_parameter_id BIGINT NOT NULL,
    result_value NUMERIC(15,4),
    result_text TEXT,
    unit_override VARCHAR(50),
    flag VARCHAR(20), -- NORMAL, HIGH, LOW, CRITICAL_HIGH, CRITICAL_LOW, ABNORMAL
    reference_range_override VARCHAR(200),
    notes TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(255),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255),
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_test_results_report FOREIGN KEY (test_report_id) REFERENCES test_reports(id) ON DELETE CASCADE,
    CONSTRAINT fk_test_results_parameter FOREIGN KEY (test_parameter_id) REFERENCES test_parameters(id) ON DELETE CASCADE
);

-- Create Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_test_types_category ON test_types(category_id);
CREATE INDEX IF NOT EXISTS idx_test_types_active ON test_types(active);
CREATE INDEX IF NOT EXISTS idx_test_parameters_type ON test_parameters(test_type_id);
CREATE INDEX IF NOT EXISTS idx_test_parameters_active ON test_parameters(active);
CREATE INDEX IF NOT EXISTS idx_test_reports_patient ON test_reports(patient_id);
CREATE INDEX IF NOT EXISTS idx_test_reports_type ON test_reports(test_type_id);
CREATE INDEX IF NOT EXISTS idx_test_reports_date ON test_reports(report_date);
CREATE INDEX IF NOT EXISTS idx_test_reports_status ON test_reports(status);
CREATE INDEX IF NOT EXISTS idx_test_reports_number ON test_reports(report_number);
CREATE INDEX IF NOT EXISTS idx_test_results_report ON test_results(test_report_id);
CREATE INDEX IF NOT EXISTS idx_test_results_parameter ON test_results(test_parameter_id);

-- Insert Test Categories
INSERT INTO test_categories (name, description) VALUES
('Blood Tests', 'Laboratory tests performed on blood samples'),
('Urine Tests', 'Laboratory tests performed on urine samples'),
('Imaging', 'Diagnostic imaging and radiology tests'),
('Microbiology', 'Microbiological culture and sensitivity tests'),
('Biochemistry', 'Clinical biochemistry and chemical analysis'),
('Immunology', 'Immunological and serological tests'),
('Hematology', 'Blood cell counts and coagulation studies'),
('Endocrinology', 'Hormone and endocrine function tests'),
('Cardiology', 'Cardiac markers and cardiovascular tests'),
('Pathology', 'Histopathology and cytology tests');

-- Insert Blood Test Types
INSERT INTO test_types (category_id, name, code, description, sample_type, turnaround_time_hours) VALUES
(1, 'Complete Blood Count', 'CBC', 'Full blood count including RBC, WBC, platelets', 'EDTA Blood', 4),
(1, 'Liver Function Test', 'LFT', 'Panel of tests to assess liver function', 'Serum', 6),
(1, 'Kidney Function Test', 'KFT', 'Panel of tests to assess kidney function', 'Serum', 6),
(1, 'Lipid Profile', 'LIPID', 'Cholesterol and triglyceride panel', 'Serum', 8),
(8, 'Thyroid Function Test', 'TFT', 'TSH, T3, T4 hormone levels', 'Serum', 24),
(9, 'Cardiac Markers', 'CARDIAC', 'Troponin, CK-MB, CPK levels', 'Serum', 2);

-- Insert Urine Test Types  
INSERT INTO test_types (category_id, name, code, description, sample_type, turnaround_time_hours) VALUES
(2, 'Routine Urine Examination', 'URE', 'Complete urine analysis', 'Fresh Urine', 2),
(2, 'Urine Culture', 'UC', 'Bacterial culture and sensitivity', 'Sterile Urine', 48),
(2, 'Urine Microscopy', 'UM', 'Microscopic examination of urine', 'Fresh Urine', 1);

-- Insert Imaging Test Types
INSERT INTO test_types (category_id, name, code, description, sample_type, turnaround_time_hours) VALUES
(3, 'X-Ray Chest PA', 'CXR', 'Posterior-anterior chest X-ray', 'N/A', 2),
(3, 'CT Scan Brain', 'CT_BRAIN', 'Computed tomography of brain', 'N/A', 4),
(3, 'MRI Spine', 'MRI_SPINE', 'Magnetic resonance imaging of spine', 'N/A', 6),
(3, 'Ultrasound Abdomen', 'USG_ABD', 'Abdominal ultrasound examination', 'N/A', 2);

-- Insert Microbiology Test Types
INSERT INTO test_types (category_id, name, code, description, sample_type, turnaround_time_hours) VALUES
(4, 'Blood Culture', 'BC', 'Bacterial culture from blood', 'Blood', 72),
(4, 'Sputum Culture', 'SC', 'Culture and sensitivity from sputum', 'Sputum', 48),
(4, 'Wound Swab Culture', 'WSC', 'Culture from wound swab', 'Swab', 48);

-- Insert Biochemistry Test Types
INSERT INTO test_types (category_id, name, code, description, sample_type, turnaround_time_hours) VALUES
(5, 'Random Blood Sugar', 'RBS', 'Random glucose level', 'Serum', 2),
(5, 'HbA1c', 'HBA1C', 'Glycated hemoglobin', 'EDTA Blood', 6),
(5, 'Serum Electrolytes', 'ELECTRO', 'Sodium, Potassium, Chloride levels', 'Serum', 4);

-- Insert Immunology Test Types
INSERT INTO test_types (category_id, name, code, description, sample_type, turnaround_time_hours) VALUES
(6, 'HIV Screening', 'HIV', 'HIV antibody/antigen test', 'Serum', 24),
(6, 'Hepatitis B Surface Antigen', 'HBSAG', 'HBsAg screening test', 'Serum', 6),
(6, 'Anti-HCV', 'HCV', 'Hepatitis C antibody test', 'Serum', 24);

-- Insert CBC Parameters
INSERT INTO test_parameters (test_type_id, name, code, unit, reference_min, reference_max, display_order) VALUES
(1, 'Hemoglobin', 'HB', 'g/dL', 12.0, 16.0, 1),
(1, 'Red Blood Cell Count', 'RBC', '10^6/uL', 4.5, 5.5, 2),
(1, 'White Blood Cell Count', 'WBC', '10^3/uL', 4.0, 11.0, 3),
(1, 'Platelet Count', 'PLT', '10^3/uL', 150.0, 450.0, 4),
(1, 'Hematocrit', 'HCT', '%', 36.0, 48.0, 5),
(1, 'Mean Corpuscular Volume', 'MCV', 'fL', 80.0, 100.0, 6),
(1, 'Mean Corpuscular Hemoglobin', 'MCH', 'pg', 27.0, 32.0, 7),
(1, 'Mean Corpuscular Hemoglobin Concentration', 'MCHC', 'g/dL', 32.0, 36.0, 8);

-- Insert LFT Parameters
INSERT INTO test_parameters (test_type_id, name, code, unit, reference_min, reference_max, display_order) VALUES
(2, 'Total Bilirubin', 'TBIL', 'mg/dL', 0.2, 1.2, 1),
(2, 'Direct Bilirubin', 'DBIL', 'mg/dL', 0.0, 0.3, 2),
(2, 'Indirect Bilirubin', 'IBIL', 'mg/dL', 0.2, 0.9, 3),
(2, 'Alanine Aminotransferase', 'ALT', 'U/L', 7.0, 56.0, 4),
(2, 'Aspartate Aminotransferase', 'AST', 'U/L', 10.0, 40.0, 5),
(2, 'Alkaline Phosphatase', 'ALP', 'U/L', 44.0, 147.0, 6),
(2, 'Total Protein', 'TP', 'g/dL', 6.0, 8.3, 7),
(2, 'Albumin', 'ALB', 'g/dL', 3.5, 5.0, 8);

-- Insert KFT Parameters
INSERT INTO test_parameters (test_type_id, name, code, unit, reference_min, reference_max, display_order) VALUES
(3, 'Blood Urea Nitrogen', 'BUN', 'mg/dL', 7.0, 20.0, 1),
(3, 'Serum Creatinine', 'CREAT', 'mg/dL', 0.6, 1.2, 2),
(3, 'Uric Acid', 'UA', 'mg/dL', 3.5, 7.2, 3),
(3, 'eGFR', 'EGFR', 'mL/min/1.73m²', 90.0, 120.0, 4);

-- Insert Lipid Profile Parameters
INSERT INTO test_parameters (test_type_id, name, code, unit, reference_min, reference_max, display_order) VALUES
(4, 'Total Cholesterol', 'CHOL', 'mg/dL', 0.0, 200.0, 1),
(4, 'Triglycerides', 'TG', 'mg/dL', 0.0, 150.0, 2),
(4, 'HDL Cholesterol', 'HDL', 'mg/dL', 40.0, 999.0, 3),
(4, 'LDL Cholesterol', 'LDL', 'mg/dL', 0.0, 100.0, 4),
(4, 'VLDL Cholesterol', 'VLDL', 'mg/dL', 0.0, 30.0, 5);

-- Insert Thyroid Function Parameters
INSERT INTO test_parameters (test_type_id, name, code, unit, reference_min, reference_max, display_order) VALUES
(5, 'Thyroid Stimulating Hormone', 'TSH', 'mIU/L', 0.4, 4.0, 1),
(5, 'Free Thyroxine', 'FT4', 'ng/dL', 0.8, 1.8, 2),
(5, 'Free Triiodothyronine', 'FT3', 'pg/mL', 2.3, 4.2, 3);

-- Insert Cardiac Marker Parameters
INSERT INTO test_parameters (test_type_id, name, code, unit, reference_min, reference_max, display_order) VALUES
(6, 'Troponin I', 'TROP_I', 'ng/mL', 0.0, 0.04, 1),
(6, 'CK-MB', 'CKMB', 'ng/mL', 0.0, 6.0, 2),
(6, 'Creatine Phosphokinase', 'CPK', 'U/L', 30.0, 200.0, 3);

-- Insert Urine Examination Parameters
INSERT INTO test_parameters (test_type_id, name, code, unit, reference_text, parameter_type, display_order) VALUES
(7, 'Colour', 'COLOR', '', 'Pale Yellow', 'TEXT', 1),
(7, 'Transparency', 'TRANS', '', 'Clear', 'TEXT', 2),
(7, 'Specific Gravity', 'SG', '', '1.010-1.025', 'NUMERIC', 3),
(7, 'pH', 'PH', '', '5.0-8.0', 'NUMERIC', 4),
(7, 'Protein', 'PROT', '', 'Nil', 'TEXT', 5),
(7, 'Glucose', 'GLU', '', 'Nil', 'TEXT', 6),
(7, 'Ketones', 'KET', '', 'Nil', 'TEXT', 7),
(7, 'Blood', 'BLOOD', '', 'Nil', 'TEXT', 8);

-- Insert Biochemistry Parameters
INSERT INTO test_parameters (test_type_id, name, code, unit, reference_min, reference_max, display_order) VALUES
(13, 'Random Glucose', 'RGL', 'mg/dL', 70.0, 140.0, 1),
(14, 'HbA1c', 'A1C', '%', 4.0, 6.0, 1),
(15, 'Sodium', 'NA', 'mEq/L', 136.0, 145.0, 1),
(15, 'Potassium', 'K', 'mEq/L', 3.5, 5.1, 2),
(15, 'Chloride', 'CL', 'mEq/L', 98.0, 107.0, 3);

-- Insert Immunology Parameters (Text results)
INSERT INTO test_parameters (test_type_id, name, code, reference_text, parameter_type, display_order) VALUES
(16, 'HIV Result', 'HIV_RES', 'Non-Reactive', 'TEXT', 1),
(17, 'HBsAg Result', 'HBSAG_RES', 'Non-Reactive', 'TEXT', 1),
(18, 'Anti-HCV Result', 'HCV_RES', 'Non-Reactive', 'TEXT', 1);

-- Create sequence for report numbers
CREATE SEQUENCE IF NOT EXISTS test_report_number_seq START 1000;

-- Function to generate report numbers
CREATE OR REPLACE FUNCTION generate_report_number() RETURNS VARCHAR(100) AS $$
BEGIN
    RETURN 'RPT-' || TO_CHAR(CURRENT_DATE, 'YYYY') || '-' || LPAD(nextval('test_report_number_seq')::TEXT, 6, '0');
END;
$$ LANGUAGE plpgsql;

-- Add trigger to auto-generate report numbers
CREATE OR REPLACE FUNCTION set_report_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.report_number IS NULL THEN
        NEW.report_number := generate_report_number();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_report_number
    BEFORE INSERT ON test_reports
    FOR EACH ROW EXECUTE FUNCTION set_report_number();
