
INSERT INTO medical_college (name, state_id, university_id, created_by, created_time, modified_by, modified_time)
VALUES
('Andaman & Nicobar Islands Institute of Medical Sciences, Port Blair', 32, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	ACSR Government Medical College Nellore', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	All India Institute of Medical Sciences, Mangalagiri, Vijayawada', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Alluri Sitaram Raju Academy of Medical Sciences, Eluru', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Andhra Medical College, Visakhapatnam', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Apollo Institute of Medical Sciences and Research, Chittoor', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. P.S.I. Medical College , Chinoutpalli', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Fathima Instt. of Medical Sciences,Kadapa', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gayathri Vidya Parishad Institute of Health Care & Medical Technology, Visakhapatnam', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GITAM Institute of Medical Sciences and Research, Visakhapatnam', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Government Medical College, Ananthapuram', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Government Medical College, Eluru', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kadapa', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Machilipatnam', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Government Medical College, Nandyal', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Government Medical College, Ongole (Previously known as Rajiv Gandhi Institute of Medical Sciences, Ongole,)', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Paderu', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Rajamahendravaram', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Vizianagaram', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Siddhartha Medical College, Vijaywada', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Great Eastern Medical School and Hospital,Srikakulam', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GSL Medical College, Rajahmundry', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Guntur Medical College, Guntur', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Katuri Medical College, Guntur', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Konaseema Institute of Medical Sciences & Research Foundation, Amalapuram', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kurnool Medical College, Kurnool', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharajah Institute of Medical Sciences, Vizianagaram', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Narayana Medical College, Nellore', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Nimra Institute of Medical Sciences, Krishna Dist., A.P.', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('NRI Institute of Medical Sciences, Visakhapatnam', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('NRI Medical College, Guntur', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('P E S Institute Of Medical Sciences and Research, Kuppam', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Rajiv Gandhi Institute of Medical Sciences, Srikakulam', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Rangaraya Medical College, Kakinada', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Santhiram Medical College, Nandyal', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Balaji Medical College, Hospital and Research Institute, Chittoor', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SVIMS - Sri Padmavathi Medical College for Women, Alipiri Road, Tirupati', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('S V Medical College, Tirupati', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Viswabharathi Medical College, Kurnool', 1, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Tomo Riba Institute of Health & Medical Sciences, Naharlagun', 2, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Guwahati', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Assam Medial College, Dibrugarh', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dhubri Medical College, Dhubri', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Diphu Medical College & Hospital, Diphu, Assam', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Fakhruddin Ali Ahmed Medical College, Barpeta, Assam', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gauhati Medical College, Guwahati', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jorhat Medical College & Hospital , Jorhat', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kokrajhar Medical College', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Lakhimpur Medical College', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Nagaon Medical College', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Nalbari Medical College, Nalbari', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Silchar Medical College, Silchar', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Tezpur Medical College & Hospital, Tezpur', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	Tinsukia Medical College', 3, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('	All India Institute of Medical Sciences, Patna', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Anugrah Narayan Magadh Medical College, Gaya', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bhagwan Mahavir Institute of Medical Sciences, Pawapuri (Formely known as Vardhman Institute of Medical Sciences, Pawapuri)', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Darbhanga Medical College, Lehriasarai', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Employees State Insurance Corporation Medical College,Patna', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Bettiah', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Purnea', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Himalaya Medical College and Hospital, Patna', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Indira Gandhi Institute of Medical Sciences,Sheikhpura, Patna', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jannayak Karpoori Thakur Medical College & Hospital, Madhepura, Bihar', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jawaharlal Nehru Medical College, Bhagalpur', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Katihar Medical College, Katihar', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Lord Buddha Koshi Medical College and Hospital, Saharsa', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Madhubani Medical College, Madhubani', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mata Gujri Memorial Medical College, Kishanganj', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Nalanda Medical College, Patna', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Narayan Medical College & Hospital, Sasaram', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Netaji Subhas Medical College & Hospital, Amhara, Bihta, Patna', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Patna Medical College, Patna', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Radha Devi Jageshwari Memorial Medical College and Hospital', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shree Narayan Medical Institute and Hospital', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Krishna Medical College, Muzzafarpur', 4, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Chandigarh', 31, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Abhishek I Mishra Memorial Medical College & Research, Bhiali', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Raipur', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chandulal Chandrakar Memorial Govt. Medical College, Durg', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chhattisgarh Institute of Medical Sciences, Bilaspur', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College (Bharat Ratna Shri Atal Bihari Vajpyee Memorial Med. Col.), Rajnandgaon', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kanker', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Korba', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Mahasamund', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Late Shri Baliram Kashyap Memorial NDMC Govt. Medical College, Jagdalpur', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Late Shri Lakhi Ram Agrawal Memorial Govt. Medical College, Raigarh', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pt. J N M Medical College, Raipur', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Raipur Institute of Medical Sciences (RIMS), Raipur', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajmata Shrimati Devendra kumari Singhdeo Government Medical College, Surguja ( C.G.)', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Balaji Institute of Medical Science', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Rawatpura Sarkar Institute of Medical Sciences and Research', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Shankaracharya Institute of Medical Sciences, Bhilai', 35, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('NAMO Medical Education and Research Institute, Silvassa', 30, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, New Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Army College of Medical Sciences, New Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Atal Bihari Vajpayee Institute of Medical Sciences and Dr. RML Hospital, New Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Baba Saheb Ambedkar Medical College, Rohini, Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Hamdard Institute of Medical Sciences & Research, New Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Lady Hardinge Medical College, New Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maulana Azad Medical College, New Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('North Delhi Muncipal Corporation Medical College, Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('University College of Medical Sciences & GTB Hospital, New Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Vardhman Mahavir Medical College & Safdarjung Hospital, Delhi', 25, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Goa Medical College, Panaji', 26, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Rajkot', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Ananya College of Medicine & Research', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Banas Medical College and Research Institute, Palanpur, Gujarat', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bhagyoday Medical College', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('B J Medical College, Ahmedabad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('CU Shah Medical College, Surendra Nagar', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr.Kiran C.Patel Medical College and Research Institute', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. M.K. Shah Medical College & Research Centre, Ahmedabad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. N.D. Desai Faculty of Medical Science and Research, Nadiad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GCS Medical College, Ahmedabad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Dharpur Patan', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Gandhinagar', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Gotri, Vadodara', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Hadiyol, Himmatnagar', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Junagadh', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Navsari', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Rajpipla', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Sola, Ahmedabad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Vadnagar, Mehsana', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GMERS Medical College, Valsad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Bhavnagar', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Morbi', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Panchmahal Godhra', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Porbandar', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Surat', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gujarat Adani Institute of Medical Sciences, Bhuj', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kiran Medical College, Surat', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Medical College, Baroda', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('MP Shah Medical College,Jamnagar', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Narendra Modi Medical College, Ahmedabad (Formely known as Ahmedabad Muncipal Coporation Medical Edu. Trust Medical College)', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Nootan Medical College and Research Centre, Mehsana', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pandit Deendayal Upadhyay Medical College, Rajkot', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Parul Institute of Medical Sciences & Research, Vadodara', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pramukhswami Medical College, Karmsad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SAL Institute of Medical Sciences, Ahmedabad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SBKS Medical Instt. & Research Centre, Vadodra', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shantabaa Medical College, Amreli', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Smt. N.H.L.Municipal Medical College, Ahmedabad', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Surat Municipal Institute of Medical Education & Research, Surat', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Swaminayaran Institute of Medical Sciences & Research', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Zydus Medical College & Hospital, Dahod', 5, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Adesh Medical College and Hospital, Shahabad, Kurukshetra, Haryana', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Al Falah School of Medical Sciences & Research Centre, Faridabad', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Amrita School of Medicine, Faridabad', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('BPS Government Medical College for Women, Sonepat', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Employees State Insurance Corporation Medical College, Faridabad', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Faculty of Medicine and Health Sciences, Gurgaon (Formarly SGGST Medical College & R Centre,Gurgaon)', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kalpana Chawala Govt. Medical College, Karnal, Haryana', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharaja Agrasen Medical College, Agroha', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharishi Markandeshwar College of Medical Sciences & Research, Sadopur', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharishi Markandeshwar Institute Of Medical Sciences & Research, Mullana, Ambala', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('N.C. Medical College & Hospital, Panipat', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pt. B D Sharma Postgraduate Institute of Medical Sciences, Rohtak (Haryana)', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shaheed Hasan Khan Mewati Government Medical College, Nalhar', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Atal Bihari Vajpayee Government Medical College, Faridabad', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('World College of Medical Sciences & Researc, Jhajjar, Haryana', 6, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Bilaspur', 7, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Radhakrishnan Government Medical College, Hamirpur, H.P', 7, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Rajendar Prasad Government Medical College, Tanda, H.P', 7, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nahan, Sirmour H.P.', 7, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Indira Gandhi Medical College, Shimla', 7, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharishi Markandeshwar Medical College & Hospital, Solan', 7, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pt. Jawahar Lal Nehru Government Medical College, Chamba', 7, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Lal Bahadur Shastri Government Medical College, Mandi, HP', 7, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Acharya Shri Chander College of Medical Sciences, Jammu', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Vijaypur', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Anantnag', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Baramulla', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Handwara', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Jammu', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kathua', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Rajouri, J&K', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Srinagar', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Udhampur', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Govt. Medical College, Doda, Kashmir', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sher-I-Kashmir Instt. Of Medical Sciences, Srinagar', 8, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Deoghar', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dumka Medical College, Dighi Dumka', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Hazaribagh Medical College, Hazaribagh', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Laxmi Chandravansi Medical College & Hospital', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Manipal Tata Medical College,Baridih Jameshedpur', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('M G M Medical College, Jamshedpur', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Palamu Medical College, Palamu', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajendra Institute of Medical Sciences, Ranchi', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shahed Nirmal Mahto Medical College & Hospital, Dhanbad', 34, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Adichunchanagiri Institute of Medical Sciences Bellur', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('A J Institute of Medical Sciences & Research Centre, Mangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Akash Institute of Medical Sciences & Research Centre, Devanhalli, Bangalore, Karnataka', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Al-Ameen Medical College,Bijapur', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bangalore Medical College and Research Institute, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Basaveswara Medical College and Hospital, Chitradurga', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Belagavi Institute of Medical Sciences, Belagavi', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('BGS Global Institute of Medical Sciences, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('BGS Medical College and Hospital', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bidar Institute of Medical Sciences,Bidar', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chamrajanagar Institute of Medical Sciences, Karnataka', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chikkaballapura Institute of Medical Sciences', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chikkamagaluru Institute of Medical Sciences, Chikkamagaluru', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chitradurga Medical College and Research Institute', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr BR Ambedkar Medical College, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Chandramma Dayananda Sagar Instt. of Medical Education & Research, Harohalli, Hubli', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('East Point College of Medical Sciences & Research Centre, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Employees State Insurance Corporation Medical College, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Employees State Insurance Corporation Medical College, Gulbarga', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Father Mullers Medical College, Mangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gadag Institute of Medical Sciences, Mallasamudra, Mulgund Road, Gadag', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('G R Medical College Hospital & Research Centre', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gulbarga Institute of Medical Sciences, Gulbarga', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Hassan Institute of Medical Sciences, Hassan', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Haveri Institute of Medical Sciences, Haveri', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jagadguru Gangadhar Mahaswamigalu Moorusavirmath Medical College JGMMMC', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jawaharlal Nehru Medical College, Belgaum', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('JJM Medical College, Davangere', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('JSS Medical College, Mysore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kanachur Institute of Medical Sciences, Mangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Karnataka Institute of Medical Sciences, Hubballi', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Karwar Institute of Medical Sciences, Karwar', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kasturba Medical College, Mangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kasturba Medical College, Manipal', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kempegowda Institute of Medical Sciences, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Khaja Bandanawaz University - Faculty of Medical Sciences, Gulbarga', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kodagu Institute of Medical Sciences, Kodagu', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Koppal Institute of Medical Sciences, Koppal', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('K S Hegde Medical Academy, Mangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('K V G Medical College, Sullia', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahadevappa Rampure Medical College, Kalaburagi, Gulbarga', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mandya Institute of Medical Sciences, Mandya', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('M S Ramaiah Medical College, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('MVJ Medical College and Research Hospital, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mysore Medical College and Research Instt. (Prev.name Government Medical College), Mysore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Navodaya Medical College, Raichur', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('PES University Institute of Medical Sciences and Reseach Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Raichur Institute of Medical Sciences,Raichur', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajarajeswari Medical College & Hospital, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sambharam Institute of Medical Sciences & Research, Kolar', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sapthagiri Institute of Medical Sciences & Research Centre, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SDM College of Medical Sciences & Hospital, Sattur, Dharwad', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shimoga Institute of Medical Sciences,Shimoga', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Atal Bihari Vajpayee Medical College & Research Institute', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri B M Patil Medical College, Hospital & Research Centre, Vijayapura(Bijapur', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shridevi Institute of Medical Sciences & Research Hospital, Tumkur', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Siddaganga Medical College and Research Institute, Tumakuru', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('S. Nijalingappa Medical College & HSK Hospital & Research Centre, Bagalkot', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Chamundeshwari Medical College Hospital & Research Institute', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Devaraj URS Medical College, Kolar', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Madhusudan Sai Institute of Medical Sciences and Research', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Srinivas Institute of Medical Research Centre, Srinivasnagar, mangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri siddhartha Institute of Medical Sciences & Research Centre, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Siddhartha Medical College, Tumkur', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SR Patil Medical College and Hospital', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('S S Institute of Medical Sciences& Research Centre, Davangere', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('St. Johns Medical College, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Subbaiah Institute of Medical Sciences, Shimoga, Karnataka', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('The Oxford Medical College, Hospital & Research Centre, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Vijaynagar Institute of Medical Sciences, Bellary', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Vydehi Institute Of Medical Sciences & Research Centre, Bangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Yadgiri Institute of Medical Sciences, Yadgiri', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Yenepoya Medical College, Mangalore', 9, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Al-Azhar Medical College and Super Speciality Hospital, Thodupuzha', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Amala Institute of Medical Sciences, Thrissur', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Amrita School of Medicine, Elamkara, Kochi', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Azeezia Instt of Medical Science,Meeyannoor,Kollam', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Believers Church Medical College Hospital, Thiruvalla, Kerala', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Moopen s Medical College, Wayanad, Kerala', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Somervel Memorial CSI Hospital & Medical College, Karakonam, Thiruvananthapuram', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Ernakulam', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Idukki', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College (Institute of Integrated Medical Sciences), Yakkara, Palakkad', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Konni', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kottayam', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kozhikode, Calicut', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Manjeri, Malapuram Dist.', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Parippally, Kollam', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Thrissur', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Govt. Medical College,Pariyaram, Kannur (Prev. Known as Academy of Medical Sciences)', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jubilee Mission Medical College & Research Institute, Thrissur', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kannur Medical College, Kannur', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Karuna Medical College, Palakkad', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('KMCT Medical College,Kozhikode, Calicut', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Malabar Medical College, Kozhikode,Calicut', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Malankara Orthodox Syrian Church Medical College, Kolenchery', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Medical College, Thiruvananthapuram', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('M E S Medical College , Perintalmanna Malappuram Distt.Kerala', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mount Zion Medical College, Chayalode, Ezhamkulam Adoor, Pathanamthitta', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Palakkad Institute of Medical Sciences, Palakkad Kerala', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('P K Das Institute of Medical Sciences, Palakkad, Kerala', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pushpagiri Institute Of Medical Sciences and Research Centre, Tiruvalla', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sree Gokulam Medical College Trust & Research Foundation, Trivandrum', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sree Narayana Instt. of Medical Sciences, Chalakka,Ernakulam', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sree Uthradom Thiurnal Academy of Medical Sciences,Trivandrum', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('T D Medical College, Alleppey (Allappuzha)', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Travancore Medical College, Kollam', 10, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Bhopal', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Amaltas Institute of Medical Sciences, Dewas', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bundelkhand Medical College, Sagar', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chirayu Medical College and Hospital, Bairagarh,Bhopal', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gajra Raja Medical College, Gwalior', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gandhi Medical College, Bhopal', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Chhindwara, MP', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Datia, MP', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Khandwa, MP', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Ratlam', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Satna', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Seoni', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Shahdol, MP', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Shivpuri, MP', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Vidisha, MP', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Index Medical College Hospital & Research Centre,Indore', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('LNCT Medical College & Sewakunj Hospital, Indore', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('L.N. Medical College and Research Centre,Bhopal', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahaveer Institute of Medical Sciences & Research, Bhopal', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('M G M Medical College, Indore', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Netaji Subhash Chandra Bose Medical College, Jabalpur', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Peoples College of Medical Sciences & Research Centre, Bhanpur, Bhopal', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Ram Krishna College Hospital & Research Centre, Bhopal', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('RKDF Medical College Hospital & Research Centre, Jatkhedi, Bhopal', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Ruxmaniben Deepchand Gardi Medical College, Ujjain', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('School of Medical Sciences, Sri Satya Sai University of Technology and Medical Sciences', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shyam Shah Medical College, Rewa', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Aurobindo Medical College and Post Graduate Institute , Indore', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sukh Sagar Medical College & Hospital, Jabalpur', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sundarlal Patwa Govt. Medical College', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Virendra Kumar Sakhlecha Government Medical College', 11, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('ACPM Medical College, Dhule', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Nagpur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Armed Forces Medical College, Pune', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Ashwini Rural Medical College, Hospital & Research Centre, Solapur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bharati Vidyapeeth Deemed University Medical College & Hospital, Sangli', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bharati Vidyapeeth University Medical College, Pune', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bharatratna Atal Bihari Vajpayee Medical College, Pune', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('B. J. Govt. Medical College, Pune', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('B.K.L. Walawalkar Rural Medical College, Ratnagiri', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Datta Meghe Medical College, Nagpur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. D Y Patil Medical College, Hospital and Research Centre, Pimpri, Pune', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. D Y Patil Medical College, Kolhapur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. N Y Tasgaonkar Institute of Medical Science', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Panjabrao Alias Bhausaheb Deshmukh Memorial Medical College, Amravati', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Rajendra Gode Medical College, Amravati', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Shankarrao Chavan Govt. Medical College, Nanded', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Ulhas Patil Medical College & Hospital, Jalgaon', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr Vaishampayan Memorial Medical College, Solapur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr.Vasantrao Pawar Med. Col. Hosp. & Research Centre,Nasik (Prev. NDMVP Samaj Medical College)', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Vithalrao Vikhe Patil Foundations Medical College & Hospital, Ahmednagar', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Akola', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Alibag', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Ambernath', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Amravati', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical college and District Hospital, Ratnagiri', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Aurangabad', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Bhandara', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Buldhana', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Chandrapur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Gadchiroli', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Gondia', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Hingoli', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College & Hospital, Baramati', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Jalgaon', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Jalna', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Latur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Miraj', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nagpur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nandurbar', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nashik', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Osmanabad', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Parbhani', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College ,Satara', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Sindhudurg', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Washim', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Grant Medical College, Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('H.B.T. Medical College & Dr. R.N. Cooper Municipal General Hospital, Juhu, Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Indian Institute of Medical Science & Research, Jalna', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Indira Gandhi Medical College & Hospital, Nagpur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jawaharlal Nehru Medical College, Sawangi (Meghe), Wardha', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('KJ Somaiyya Medical College & Research Centre, Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Krishna Institute of Medical Sciences, Karad', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Lokmanya Tilak Municipal Medical College, Sion, Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharashtra Institute of Medical Education & Research, Talegaon,Pune', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharashtra Institute of Medical Sciences & Research, Latur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahatma Gandhi Institute of Medical Sciences, Sevagram, Wardha', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahatma Gandhi Mission Medical College, Vashi', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahatma Gandhi Missions Medical College, Aurangabad', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahatma Gandhi Missions Medical College, Navi Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahatma Gandhi Missions Medical College, Nerul, Navi Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('N. K. P. Salve Instt. of Medical Sciences and Research Centre and Lata Mangeshkar Hospital, Nagpur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Padmashree Dr. D.Y.Patil Medical College, Navi Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Parbhani Medical College, Parbhani', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Prakash Institute of Medical Sciences & Research, Sangli', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajashree Chatrapati Shahu Maharaj Government Medical College, Kolhapur', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajiv Gandhi Medical College and Chhatrapati Shivaji Maharaj Hospital, Thane', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rural Medical College, Loni', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Seth GS Medical College, and KEM Hospital, Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Ramchandra Institute of Medical Sciences, Aurangabad', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Vasant Rao Naik Govt. Medical College, Yavatmal', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sindhudurg Shikshan Prasarak Mandal (SSPM) Medical College & Lifetime Hospital, Padave, Sindhudurg', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SMBT Institute of Medical Sciences & Research Centre, Nandihills, Nashik', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Smt. Kashibai Navale Medical College and General Hospital,Pune', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Bhausaheb Hire Government Medical College, Dhule', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SRTR Medical College, Ambajogai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Symbiosis Medical College for Women, Pune', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Terna Medical College, Navi Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Topiwala National Medical College, Mumbai', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Vedantaa Institute of Medical Sciences, Palghar, Maharashtra', 12, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Churachandpur', 13, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jawaharlal Nehru Institute of Medical Sciences,Porompet,Imphal', 13, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Regional Institute of Medical Sciences, Imphal', 13, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shija Academy of Health Sciences', 13, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('North Eastern Indira Gandhi Regional Instt. of Health and Medical Sciences, Shillong', 14, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('PA Sangma International Medical College & Hospital', 14, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Zoram Medical College, Mizoram', 15, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Nagaland Institute of Medical Sciences & Research', 16, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Bhubaneswar', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dharanidhar Medical College & Hospital (DDMCH), Keonjhar,', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('DRIEMS Institute of Health Sciences and Hospital, Kairapari', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College and Hospital, Jajpur', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College & Hospital (Renamed as Bhima Bhoi Medical College & Hospital), Balangir', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College & Hospital (Renamed as Fakir Mohan Medical College & Hospital), Balasore', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Sundargarh', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Hi-Tech Medical College & Hospital, Bhubaneswar', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Hi-Tech Medical College & Hospital, Rourkela', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Institute of Medical Sciences & SUM Hospital', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Instt. Of Medical Sciences & SUM Hospital, Bhubaneswar', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kalinga Institute of Medical Sciences, Bhubaneswar', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('MKCG Medical College, Berhampur', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pt. Raghunath Murmu Medical College and Hospital, Baripada, Odisha', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Saheed Laxman Nayak Medical College & Hospital, Koraput', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Saheed Rendo Majhi Medical College & Hospital, Bhawanipatna, Kalahandi', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SCB Medical College, Cuttack', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Jagannath Medical College & Hospital, Puri', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Veer Surendra Sai Institute of Medical Sciences and Research, Burla', 17, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Aarupadai Veedu Medical College, Pondicherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Indira Gandhi Medical College & Research Institute, Puducherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jawaharlal Institute of Postgraduate Medical Education & Research, Puducherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahatma Gandhi Medical College & Research Institute, Pondicherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pondicherry Institute of Medical Sciences & Research, Pondicherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Lakshmi Narayana Institute of Medical Sciences, Pondicherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Manakula Vinayagar Medical College & Hospital, Pondicherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Venkateswaraa Medical College, Hospital & Research Centre, Pondicherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Vinayaka Missions Medical College, Karaikal, Pondicherry', 27, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Adesh Institute of Medical Sciences & Research, Bhatinda', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Bhatinda', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chintpurni Medical College, Pathankot, Gurdaspur', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Christian Medical College, Ludhiana', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dayanand Medical College & Hospital, Ludhiana', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr B R Ambedkar State Institute of Medical Sciences, SAS Nagar , Mohali', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gian Sagar Medical College & Hospital, Patiala', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Amritsar', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Patiala', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Guru Govind Singh Medical College, Faridkot', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Punjab Institute of Medical Sciences, Jalandhar', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('RIMT Medical College and Hospital', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Guru Ram Das Institute of Medical Sciences and Research, Sri Amritsar', 18, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Jodhpur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('American International Institute of Medical Sciences, Bedwas', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Ananta Institute of Medical Sciences & Research Centre, Rajsamand', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr SN Medical College, Jodhpur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr S S Tantia Medical College Hospital & Research Centre', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Employees State Insurance Corporation Medical College,Alwar', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Geetanjali Medical College & Hospital,Udaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Alwar', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Banswara', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Baran', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Barmer', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Bharatpur, Rajasthan', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Bhilwara, Rajasthan', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Bundi', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Chittorgarh', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Churu', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Dausa', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Dholpur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Dungarpur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Hanumangarh', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Jhunjhunu', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Karauli', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kota', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nagaur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Pali, Rajasthan', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Sawai Madhopur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Sirohi', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Sri Ganganagar', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jaipur National University Institute of Medical Sciences and Resarch Centre, Jagatpura, Jaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jawaharlal Nehru Medical College, Ajmer', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jhalawar Medical College, Jhalawar', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('JIET Medical College And Hospital', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahatma Gandhi Medical College and Hospital, Sitapur, Jaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('National Institute of Medical Science & Research, Jaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pacific Institute of Medical Sciences, Umarda, Udaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Pacific Medical College & Hospital, Bhilo Ka Bedla, Udaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('R N T Medical College, Udaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('RUHS College of Medical Sciences, Jaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sardar Patel Medical College, Bikaner', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Kalyan Govt. Medical College, Sikar, Rajasthan', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SMS Medical College, Jaipur', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sudha Medical College', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Vyas Medical College & Hospital', 19, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sikkim Manipal Institute of Medical Sciences, Gangtok', 20, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('ACS Medical College and Hospital, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Madurai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Annaii Medical College and Hospital', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Annapoorna Medical College & Hospital, Salem', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Arunai Medical College And Hospital', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bhaarat Medical College & Hospital', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chengalpattu Medical College, Chengalpattu', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chettinad Hospital & Research Institute, Kanchipuram', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Christian Medical College, Vellore', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Coimbatore Medical College, Coimbatore', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dhanalakshmi Srinivasan Institute of Medical Sciences and Hospital,', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dhanalakshmi Srinivasan Medical College and Hospital,Perambalur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('E.S.I.C. Medical College & Hospital, K.K. Nagar, Chennai earlier known as ESIC Medical College & PGIMSR, K.K Nagar, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Faculty of Medicine , Sri Lalithambigai Medical College and Hospital', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Dharmapuri Medical College, Dharmapuri', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Erode Medical College & Hospital, Perundurai (Formerly IRT Perundurai Medical College)', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College,Ariyalur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College,Dindigul', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College & ESIC Hospital, Coimbatore, Tamil Nadu.', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College Kallakurichi', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Karur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College Krishnagiri', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College Nagapattinam', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Namakkal', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Omandurar', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Pudukottai, Tamil Nadu', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College Ramanathapuram', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, The Nilgiris', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Thiruvallur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College ,Tiruppur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Virudhunagar', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Sivagangai Medical College, Sivaganga', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Thiruvannamalai Medical College, Thiruvannamalai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Vellore Medical College, Vellore', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Villupuram Medical College, Villupuram', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Govt. Mohan Kumaramangalam Medical College, Salem- 30', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Indira Medical College & Hospitals, Thiruvallur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('J R Medical College and Hospital', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('KanyaKumari Government Medical College, Asaripallam', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kanyakumari Medical Mission Research Centre', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('K A P Viswanathan Government Medical College, Trichy', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Karpagam Faculty of Medical Sciences & Research, Coimbatore', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Karpaga Vinayaga Institute of Medical Sciences,Maduranthagam', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kilpauk Medical College, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('KMCH Institute of Health Sciences and Research, Coimbatore', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Madha Medical College and Hospital, Thandalam, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Madras Medical College, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Madurai Medical College, Madurai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Meenakshi Medical College and Research Institute, Enathur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Melmaruvathur Adiparasakthi Instt. Medical Sciences and Research', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Nandha Medical College & Hospital Erode', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Panimalar Medical College Hospital & Research Institute, Chennai,Tamil Nadu', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('PSG Institute of Medical Sciences, Coimbatore', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('PSP Medical College Hospital and Research Institute', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajah Muthiah Medical College, Annamalainagar', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Saveetha Medical College and Hospital, Kanchipuram', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Sathya Sai Medical College and Research Institute, Kancheepuram', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sree Balaji Medical College and Hospital, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sree Mookambika Institute of Medical Sciences, Kanyakumari', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Muthukumaran Medical College,Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Srinivasan Medical College and Hospital', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Ramachandra Medical College & Research Institute, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sri Venkateswaraa Medical College Hospital and Research Institute, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SRM Medical College Hospital & Research Centre, Chengalpattu', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Stanley Medical College, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('ST Peters Medical College, Hospital & Research Institute', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Swamy Vivekanandha Medical College Hospital And Research Institute', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Tagore Medical College and Hospital, Chennai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Thanjavur Medical College,Thanjavur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Theni Government Medical College,Theni', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Thiruvarur Govt. Medical College, Thiruvarur', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Thoothukudi Medical College, Thoothukudi', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Tirunelveli Medical College,Tirunelveli', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Trichy SRM Medical College Hospital & Research Centre, Trichy', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Velammal Medical College Hospital and Research Institute, Madurai', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('VELS Medical College & Hospital', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Vinayaka Missions Kirupananda Variyar Medical College, Salem', 21, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Bibinagar', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Apollo Institute of Medical Sciences and Research, Hyderabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Arundathi Institute of Medical Sciences', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Ayaan Institute of Medical Sciences, Teaching Hospital & Research Centre, Kanaka Mamidi, R.R. Dist', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bhaskar Medical College, Yenkapally', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Chalmeda Anand Rao Insttitute Of Medical Sciences, Karimnagar', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('CMR Institute of Medical Sciences', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Deccan College of Medical Sciences, Hyderabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Patnam Mahender Reddy Institute of Medical Sciences, Chevella, Rangareddy', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. VRK Womens Medical College, Aziznagar', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Employees State Insurance Coporation Medical College, Sanath Nagar, Hyderabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Father Colombo Institute of Medical Sciences', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gandhi Medical College, Secunderabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Bhadradri Kothagudem', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Jagtial', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College Jangaon', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Jayashankar Bhupalpally', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Jogulamba', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kamareddy', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Karimnagar', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Khammam', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kumuram Bheem Asifabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Mahabubabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Mahabubnagar', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Maheshwaram', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Mancherial', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Medak', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Mulugu', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nagarkurnool', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nalgonda', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Narayanpet', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Narsampet', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nirmal', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Nizamabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government medical College, Quthbullapur', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Rajanna Sircilla', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Ramagundam', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Sangareddy', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Siddipet', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Suryapet', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Vikarabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Wanaparthy', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Yadadri', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kakatiya Medical College, Warangal', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kamineni Academy of Medical Sciences & Research Center, Hyderabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kamineni Institute of Medical Sciences, Narketpally', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahavir Institute of Medical Sciences, Vikarabad, Telengana', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maheshwara Medical College, Chitkul, Patancheru, Medak', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Malla Reddy Institute of Medical Sciences, Hyderabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mallareddy Medical College for Women, Hyderabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mamata Academy of Medical Sciences, Bachupally', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mamata Medical College, Khammam', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mediciti Institute Of Medical Sciences, Ghanpur', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('MNR Medical College & Hospital, Sangareddy', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Neelima Institute of Medical Sciences, Medchal', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Nova Institute of Medical Sciences and Research Centre', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Osmania Medical College, Hyderabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Prathima Institute Of Medical Sciences, Karimnagar', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Prathima Relief Institue of Medical Sciences', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajiv Gandhi Institute of Medical Sciences, adilabad', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('R.V.M. Institute of Medical Sciences and Research Centre, Siddipet', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shadan Institute of Medical Sciences,Research Centre and Teaching Hospital, Peerancheru', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Surabhi Institute of Medical Sciences, Siddipet, Telangana', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('S V S Medical College, Mehboobnagar', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('TRR Institute of Medical Sciences, Patancheru', 36, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Agartala Government Medical College,Agartala', 22, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Tripura Medical College and Dr. B R A M Teaching Hospital, Agartala', 22, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Tripura Santiniketan Medical College & Hospital', 22, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Rishikesh', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Doon Medical College, Dehradun, Uttarakhand', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gautam Buddha Chikitsa Mahavidyalaya, Dehradum', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical college and Hospital , Haridwar', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College (Prev.Uttarakhand Forest Hospital Trust Med.Col.), Haldwani', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Graphic Era Institute of Medical Sciences', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Himalayan Institute of Medical Sciences, Dehradun', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Guru Ram Rai Institute of Medical & Health Sciences, Dehradun', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Soban Singh Jeena Government Institute of Medical Science & Research, Almora', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Veer Chandra Singh Garhwali Govt. Medical Sc. & Research Instt, Srinagar, Pauri Garhwal', 37, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Ajay Sangaal Institute of Medical Sciences and Ayushman Hospital', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Gorakhpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Rae Bareli', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College, Akbarpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College and Hospital Auraiya', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College and Hospital Gonda', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College and Hospital Kaushambi', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College and Hospital Lakhimpuri kheri', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College Kushinagar', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College, Lalitpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College Pilibhit', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College Pratapgarh', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College, Siddharthnagar', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College Society, Etah, Uttar Pradesh', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College Society, Fatehpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College Society Ghazipur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College Society, Hardoi', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College, Sonebhadra', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Medical College Sultanpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Autonomous State Society Medical College Mirzapur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Baba Kina Ram Autonomous State Medical College and Hospital', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('BRD Medical College, Gorakhpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Career Instt. Of Medical Sciences & Hospital, Lucknow', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. B.S. Kushwah Institute of Medical Sciences', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Dr. Ram Manohar Lohia Institute of Medical Sciences,Lucknow', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Era Lucknow Medical College , Lucknow', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('F.H. Medical College & Hospital, Etamdapur, Agra', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Allopathic Medical College, Banda, UP', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Institute of Medical Sciences, Kasna, Greater Noida', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Badaun, U.P.', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Faizabad', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Firozabad', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Kannauj', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Rampur, Basti', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College, Shahjahanpur, UP', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Government Medical College & Super facility Hospital, Azamgarh', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('G.S. Medical College & Hospital, Hapur, UP', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('GSVM Medical College, Kanpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Heritage Institute of Medical Sciences, Varanasi', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Hind Institute of Medical Sciences , Barabanki', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Hind Institute of Medical Sciences, Sitapur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Institute of Medical Sciences, BHU, Varansi', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Integral Institute of Medical Sciences & Research, Lucknow', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jawaharlal Nehru Medical College, Aligarh', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Kalyan Singh Government Medical College, Hospital and Kasturba Mahila Chikitsalaya', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('K.D. Medical College Hospital & Research Centre, Mathura', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('King George Medical University, Lucknow', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('KMC Medical College & Hospital', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Krishna Mohan Medical College & Hospital, Mathura', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('LLRM Medical College, Meerut', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahamaya Rajkiya Allopathic Medical College, Ambedkarnagar', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharani Laxmi Bai Medical College, Jhansi', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Maharshi Devraha Baba Autonomous State Medical College, Deoria', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mahatma Vidur Autonomous State Medical College', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Major S D Singh Medical College and Hospital, Fathehgarh, Farrukhabad', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Mayo Institute of Medical Sciences, Barabanki', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Moti Lal Nehru Medical College, Allahabad', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Muzaffarnagar Medical College, Muzaffarnagar', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Naraina Medical College & Research Centre', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('National Capital Region Institute of Medical Sciences, Meerut', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Noida International Institute Of Medical Sciences', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Prasad Institute of Medical Sciences, Lucknow', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajkiya Allopathic Medical College, Bahraich, UP', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajkiya Medical College Jalaun, Orai, Uttar Pradesh', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rajshree Medical Research Institute, Bareilly', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rama Medical College and Hospital , Kanpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rama Medical College Hospital and Research Centre, Hapur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rohilkhand Medical College & Hospital, Bareilly', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Santosh Medical College, Ghaziabad', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Saraswati Institute of Medical Sciences, Hapur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Saraswati Medical College, Unnao, U.P.', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('School of Medical Sciences & Research,Greater Noida', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shaikh-UL-Hind Maulana Mahmood Hasan Medical College, Saharanpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Gorakshnath Medical College Hospital & Research Centre', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Ram Murti Smarak Institute of Medical Sciences, Bareilly', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Siddhi Vinayak Medical College & Hospital', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('SKS Hospital Medical College & Research Centre', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('S N Medical College, Agra', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Subharti Medical College, Meerut', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Teerthanker Mahaveer Medical College, Moradabad', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('T S Misra Medical College & Hospital, Amusi, Lucknow', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Uma Nath Singh Autonomous State Medical College Society Jaunpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('United Institute of Medical Sciences, Allahabad', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Uttar Pradesh University of Medical Sciences, (Prev. UP Rural Inst.of Med.Sc&R) Etawah', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Varun Arjun Medical College, Banthra, Shahjahanpur', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Venkateshwara Institute of Medical Sciences, Gajraula', 23, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('All India Institute of Medical Sciences, Kalyani, Nadia', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Bankura Sammilani Medical College, Bankura', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Barasat Government Medical College & Hospital', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Burdwan Medical College, Burdwan', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Calcutta National Medical College, Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('College of Medicine and JNM Hospital,Kalyani,Nadia', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('College of Medicine and Sagore Dutta Hospital, Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Coochbehar Government Medical College & Hospital, Coochbehar, WB', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Diamond Harbour Government Medical College and Hospital, West Bengal', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('East West Institute of Medical Sciences and Research', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Employees State Insurance Corporation Medical College, Joka, Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Gouri Devi Institute of Medical Sciences and Hospital, Durgapur', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Govt. Medical College, Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('ICARE Institute of Medical Sciences & Research, Haldia, Purba Midanpore', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Institute of Postgraduate Medical Education & Research, Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('IQ-City Medical College, Burdwan', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jagannath Gupta Institute of Medical Sciences & Hospital, Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jakir Hossain Medical College and Research Institute', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jalpaiguri Government Medical College', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Jhargram Government Medical College & Hospital', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('JIS School of Medical Science & Research, Howrah', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('JMN Medical College, Nadia', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('KPC Medical College,Jadavpur,Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Krishnanagar Institute of Medical Sciences', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Malda Medical College & Hospital, Malda', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Midnapore Medical College, Midnapore', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Murshidabad Medical College & Hospitals, Murshidabad', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Nilratan Sircar Medical College, Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('North Bengal Medical College, Darjeeling', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Prafulla Chandra Sen Government Medical College & Hospital', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Purulia Government Medical College & Hospital', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Raiganj Government Medical College & Hospital, Raiganj', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Rampurhat Government Medical College & Hospital, Rampurhat', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('RG Kar Medical College, Kolkata', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Santiniketan Medical College, Bolpur, West Bengal', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Sarat Chandra Chattopadhyay Government Medical College & Hospital', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Shri Ramkrishna Institute of Medical Sciences & Sanaka Hospitals, Durgapur', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL),
('Tamralipto Government Medical College & Hospital', 24, NULL, 'system', CURRENT_TIMESTAMP, NULL, NULL);
