
-- Create lab_orders table
CREATE TABLE lab_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT, -- optional, if linked to visits
    patient_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    order_number VARCHAR(100) UNIQUE NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED, CANCELLED
    priority VARCHAR(20) DEFAULT 'ROUTINE', -- URGENT, ROUTINE, STAT
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expected_date TIMESTAMP,
    referring_doctor VARCHAR(200),
    comments TEXT,
    created_by VARCHAR(255),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255),
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lab_orders_patient FOREIGN KEY (patient_id) REFERENCES patient(id) ON DELETE CASCADE,
    CONSTRAINT fk_lab_orders_branch FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE CASCADE
);

-- Create lab_order_items table
CREATE TABLE lab_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_order_id BIGINT NOT NULL,
    test_type_id BIGINT NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING', -- PENDING, COMPLETED, CANCELLED
    sample_collected BOOLEAN DEFAULT FALSE,
    sample_collection_date TIMESTAMP,
    created_by VARCHAR(255),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255),
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lab_order_items_order FOREIGN KEY (lab_order_id) REFERENCES lab_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_lab_order_items_test FOREIGN KEY (test_type_id) REFERENCES test_types(id) ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX idx_lab_orders_patient_id ON lab_orders(patient_id);
CREATE INDEX idx_lab_orders_branch_id ON lab_orders(branch_id);
CREATE INDEX idx_lab_orders_order_number ON lab_orders(order_number);
CREATE INDEX idx_lab_orders_status_v2 ON lab_orders(status);
CREATE INDEX idx_lab_orders_order_date ON lab_orders(order_date);
CREATE INDEX idx_lab_order_items_lab_order_id ON lab_order_items(lab_order_id);
CREATE INDEX idx_lab_order_items_test_type_id ON lab_order_items(test_type_id);
CREATE INDEX idx_lab_order_items_status_v2 ON lab_order_items(status);
