package com.jee.clinichub.global.utility;

import java.util.UUID;

public class SlugUtil {

	/**
	 * Converts a given string into a URL-friendly slug. The slug is generated by
	 * converting the string to lowercase, removing special characters, replacing
	 * spaces with hyphens, and appending a random 6-character UUID suffix.
	 *
	 * @param input the input string to be converted into a slug
	 * @return a URL-friendly slug with a 6-character UUID suffix, or null if the
	 *         input is null
	 */
	public static String toSlug(String input) {
        if (input == null) return null;

        String base = input.trim().toLowerCase()
                .replaceAll("[^a-z0-9\\s]", "")
                .replaceAll("\\s+", "-");

        return base + "-" + UUID.randomUUID().toString().substring(0, 6); // 6-char suffix
    }
}